import type { SettingField, SettingOption, SettingTabCycle } from "./settings.js";
export type ModelThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
export interface ModelSelectionOption extends SettingOption<string> { readonly label: string; }
export interface ModelSelectionCandidate { readonly provider: string; readonly id: string; }
export interface ModelSelectionRegistry<T extends ModelSelectionCandidate> { getAvailable?(): readonly T[]; getRegisteredProviderIds(): readonly string[]; hasConfiguredAuth(model: T): boolean; }
export interface ModelThinkingCycle { readonly fieldId: string; readonly label: string; readonly description: string; readonly defaultValue: ModelThinkingLevel; readonly options: readonly SettingOption<ModelThinkingLevel>[]; }
export interface CreateModelSelectionFieldOptions { readonly id: string; readonly label: string; readonly description: string; readonly modelOptions: readonly ModelSelectionOption[]; readonly thinking: ModelThinkingLevel | ModelThinkingCycle; }
export function thinkingGlyph(level: unknown): string { if (level === "off" || level === "minimal") return "○"; if (level === "low") return "◔"; if (level === "medium") return "◑"; if (level === "high") return "◕"; if (level === "xhigh" || level === "max") return "●"; return "?"; }
export function modelSelectionOptions(models: Iterable<ModelSelectionCandidate>): readonly ModelSelectionOption[] { const values = new Set<string>(); for (const model of models) values.add(`${model.provider}/${model.id}`); return [{ value: "", label: "Not set" }, ...[...values].sort().map(value => ({ value, label: value }))]; }
export function authenticatedModelSelectionOptions<T extends ModelSelectionCandidate>(registry: ModelSelectionRegistry<T>): readonly ModelSelectionOption[] { return modelSelectionOptions((registry.getAvailable?.() ?? []).filter(model => registry.hasConfiguredAuth(model))); }
export function createModelSelectionField(options: CreateModelSelectionFieldOptions): SettingField<string> { const cycle = typeof options.thinking === "string" ? undefined : options.thinking; const fixed = typeof options.thinking === "string" ? options.thinking : undefined; const thinking = (value: unknown): ModelThinkingLevel => ["off","minimal","low","medium","high","xhigh","max"].includes(value as string) ? value as ModelThinkingLevel : cycle?.defaultValue ?? fixed ?? "off"; const text = (value: string): string => value.trim() || "Not set"; const tabCycle: SettingTabCycle | undefined = cycle ? { ...cycle, separator: " " } : undefined; return { id: options.id, label: options.label, type: "enum", defaultValue: "", description: options.description, options: options.modelOptions, formatDisplay: (value, related) => `${thinkingGlyph(thinking(related))} ${text(value)}`, formatDescription: (value, related) => `${text(value)} ${thinking(related)}`, parse: draft => draft, validate: value => value.length > 0 && !/^[^/\s]+\/[^/\s]+$/u.test(value) ? "Use provider/model" : undefined, ...(tabCycle === undefined ? {} : { tabCycle }) }; }
