import { type RuntimeHost, runtimeIdentity } from "./runtime-identity.js";
export type SettingPrimitive = boolean | number | string;
export type SettingValue = SettingPrimitive | null;
export type SettingsState = Record<string, Record<string, SettingValue>>;
export interface Context { readonly sessionId: string; readonly signal?: AbortSignal; readonly cwd?: string; readonly [key: string]: unknown; }
export type SettingType = "boolean" | "enum" | "text" | "number" | "path";
export interface SettingOption<T extends SettingPrimitive = SettingPrimitive> { readonly value: T; readonly label?: string; readonly description?: string; }
export interface SettingTabCycle { readonly fieldId: string; readonly label: string; readonly description: string; readonly defaultValue: SettingPrimitive; readonly options: readonly SettingOption[]; readonly separator?: string; }
export interface SettingField<T extends SettingPrimitive = SettingPrimitive> { readonly id: string; readonly label: string; readonly type: SettingType; readonly defaultValue: T; readonly description: string; readonly options?: readonly SettingOption<T>[]; readonly tabCycle?: SettingTabCycle; format?(value: T): string; formatDisplay?(value: T, relatedValue?: SettingPrimitive): string; formatDescription?(value: T, relatedValue?: SettingPrimitive): string; parse(draft: string): T; validate?(value: T): string | undefined; enabled?(state: SettingsState): boolean; }
export interface SettingGroup { readonly id: string; readonly title: string; readonly description?: string; readonly fields: readonly SettingField[]; }
export interface SettingChange { readonly groupId: string; readonly fieldId: string; readonly value: SettingValue; readonly previousValue?: SettingValue; readonly state: SettingsState; }
export interface SettingsStorage { load(ctx: Context): SettingsState | undefined | Promise<SettingsState | undefined>; save(state: SettingsState, ctx: Context): void | Promise<void>; validate?(state: SettingsState, ctx: Context): void | Promise<void>; close?(ctx: Context): void | Promise<void>; }
export interface SettingsProvider { readonly id: string; readonly title: string; readonly moduleName?: string; readonly origin?: string; readonly description?: string; readonly groups: readonly SettingGroup[]; readonly panels?: readonly Panel[]; readonly storage: SettingsStorage; readonly onLoad?: (state: SettingsState, ctx: Context) => void | Promise<void>; readonly onChange?: (change: SettingChange, ctx: Context) => void | Promise<void>; readonly onClose?: (state: SettingsState, ctx: Context) => void | Promise<void>; }
export interface SettingsRegistry { register(provider: SettingsProvider): () => void; replace(provider: SettingsProvider): () => void; list(options?: { includeEmpty?: boolean }): readonly SettingsProvider[]; get(id: string): SettingsProvider | undefined; }
const registries = new WeakMap<object, SettingsRegistry>();
class Registry implements SettingsRegistry { readonly providers = new Map<string, SettingsProvider>(); register(p: SettingsProvider): () => void { if (this.providers.has(p.id)) throw new Error(`Settings provider id collision: ${p.id}`); return this.set(p); } replace(p: SettingsProvider): () => void { return this.set(p); } list(o: { includeEmpty?: boolean } = {}): readonly SettingsProvider[] { return [...this.providers.values()].filter(p => o.includeEmpty === true || p.groups.some(g => g.fields.length > 0) || (p.panels?.length ?? 0) > 0).sort((a,b) => a.title.localeCompare(b.title) || a.id.localeCompare(b.id)); } get(id: string): SettingsProvider | undefined { return this.providers.get(id); } private set(p: SettingsProvider): () => void { this.providers.set(p.id,p); return () => { if (this.providers.get(p.id) === p) this.providers.delete(p.id); }; } }
export function getRuntimeSettingsRegistry(host: RuntimeHost): SettingsRegistry { const key = runtimeIdentity(host); const found = registries.get(key); if (found !== undefined) return found; const created = new Registry(); registries.set(key, created); return created; }
export function createSettingsRegistry(): SettingsRegistry { return new Registry(); }
export function registerSettings(p: SettingsProvider, r: SettingsRegistry): () => void { return r.register(p); }
export function replaceSettings(p: SettingsProvider, r: SettingsRegistry): () => void { return r.replace(p); }
export function listSettings(r: SettingsRegistry, o?: { includeEmpty?: boolean }): readonly SettingsProvider[] { return r.list(o); }
export function getSettings(id: string, r: SettingsRegistry): SettingsProvider | undefined { return r.get(id); }
export function createSessionStorage(): SettingsStorage { const states = new Map<string, SettingsState>(); return { load: ctx => states.get(ctx.sessionId), save: (state, ctx) => { states.set(ctx.sessionId, state); } }; }
