export {
	AUTO_TITLE_FIELD,
	AUTO_TITLE_GROUP,
	AUTO_TITLE_MODEL_FIELD,
	AUTO_TITLE_SETTINGS_PROVIDER_ID,
	AUTO_TITLE_SYSTEM_PROMPT,
	type AutoTitleAgentAdapter,
	type AutoTitleAgentFactory,
	type AutoTitleCoordinator,
	type AutoTitleModelOption,
	type AutoTitleRuntime,
	type AutoTitleSettingsOptions,
	type AutoTitleStorageOptions,
	createAutoTitleCoordinator,
	createAutoTitleSettingsProvider,
	createAutoTitleStorage,
	createCoreAutoTitleAgent,
	parseModelRef,
	safeTitle,
} from "./auto-title.js";
export {
	applyBatchToolRules,
	BATCH_TOOL_RULES_CUSTOM_FIELD,
	BATCH_TOOL_RULES_ENABLED_FIELD,
	BATCH_TOOL_RULES_GROUP,
	BATCH_TOOL_RULES_SECTION,
	BATCH_TOOL_RULES_SETTINGS_PROVIDER_ID,
	type BatchToolRulesConfig,
	type BatchToolRulesSettingsOptions,
	buildBatchToolPrompt,
	buildDefaultBatchToolPrompt,
	createBatchToolRulesSettingsProvider,
	createBatchToolRulesStorage,
	DEFAULT_BATCH_TOOL_RULES_CONFIG,
	normalizeBatchToolRulesConfig,
} from "./batch-tool-rules.js";
export {
	CODEMODE_REMINDER_CUSTOM_TYPE,
	type CodemodeGuard,
	type CodemodeGuardOptions,
	createCodemodeGuard,
	DEFAULT_CODEMODE_BATCH_REMINDER,
	DEFAULT_CODEMODE_GUARD_THRESHOLD,
	isGeminiModel,
} from "./codemode-guard.js";
export {
	createDollarSkillAtomicEditor,
	createDollarSkillAutocompleteProvider,
	createDollarSkillFeature,
	createDollarSkillSettingsProvider,
	DEFAULT_DOLLAR_SKILL_CONFIG,
	DEFAULT_DOLLAR_SKILL_MAX_SUGGESTIONS,
	DOLLAR_SKILL_SETTINGS_GROUP,
	type DollarSkillCommand,
	type DollarSkillConfig,
	type DollarSkillFeature,
	type DollarSkillToken,
	dollarSkillSettingsPath,
	expandDollarSkillReferences,
	extractDollarSkillToken,
	getDollarSkillSuggestions,
	loadDollarSkillConfig,
	MAX_DOLLAR_SKILL_SUGGESTIONS,
	normalizeDollarSkillConfig,
	registerDollarSkillInputTransform,
	saveDollarSkillConfig,
} from "./dollar-skill/index.js";
export { default } from "./extension.js";
export {
	registerGeminiThoughtGuard,
	sanitizeGeminiThoughtSignatures,
} from "./gemini-thought-guard.js";
export {
	is409SessionError,
	isGptModel,
	RECOVERY_ERROR_409_PATTERN,
	registerSessionRecoveryGuard,
	type SessionRecoveryGuard,
	stripEncryptedThinking,
} from "./session-recovery-guard.js";
